package edu.mit.media.mysnapshot.backend;

import org.junit.Test;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

/**
 * Characterization tests for the adaptive experiment engine (Phase 0 of
 * AGENT_PLANS/MODERNIZE.md). Expected values are hand-derived directly from
 * AffectiveComputingQuantifyMeDjango/src/app/models.py + analysis.py (the ground
 * truth being deleted as a runtime dependency in Phase 2), NOT generated by running
 * {@link ExperimentEngineReference} against itself. Every later port of this logic
 * (Phase 2's Kotlin/Room engine) must keep passing these unchanged.
 */
public class ExperimentEngineCharacterizationTest {

    // SleepDurationProductivity.get_ranges() / get_range_size(), in minutes.
    private static Map<String, Double> sleepDurationRanges() {
        Map<String, Double> ranges = new HashMap<>();
        ranges.put("under", 360.0); // 6h
        ranges.put("N1", 390.0);    // 6.5h
        ranges.put("N2", 450.0);    // 7.5h
        ranges.put("N3", 510.0);    // 8.5h
        ranges.put("over", 540.0);  // 9h
        return ranges;
    }

    private static final double SLEEP_DURATION_RANGE_SIZE = 30.0;

    // SleepVariabilityStress.get_ranges() / get_range_size(), in minutes.
    private static Map<String, Double> sleepVariabilityRanges() {
        Map<String, Double> ranges = new HashMap<>();
        ranges.put("under", 15.0);
        ranges.put("N1", 30.0);
        ranges.put("N2", 60.0);
        ranges.put("N3", 90.0);
        ranges.put("over", 105.0);
        return ranges;
    }

    private static final double SLEEP_VARIABILITY_RANGE_SIZE = 15.0;

    private static List<Double> constant(double v, int n) {
        Double[] arr = new Double[n];
        Arrays.fill(arr, v);
        return Arrays.asList(arr);
    }

    // ---- set_stage_targets ----------------------------------------------------------

    @Test
    public void setStageTargets_underRange_targetsUnderN1N3N2() {
        ExperimentEngineReference.StageTargets r = ExperimentEngineReference.setStageTargets(
                constant(360.0, 7), false, sleepDurationRanges(), SLEEP_DURATION_RANGE_SIZE);
        assertEquals(360.0, r.initialStageAverage, 1e-9);
        assertArrayEquals(new double[]{360, 390, 510, 450}, r.stageTargetValues);
    }

    @Test
    public void setStageTargets_n1Range_targetsN1N3N1N2() {
        ExperimentEngineReference.StageTargets r = ExperimentEngineReference.setStageTargets(
                constant(420.0, 7), false, sleepDurationRanges(), SLEEP_DURATION_RANGE_SIZE);
        assertArrayEquals(new double[]{390, 510, 390, 450}, r.stageTargetValues);
    }

    @Test
    public void setStageTargets_n2Range_targetsN2N3N1N2() {
        ExperimentEngineReference.StageTargets r = ExperimentEngineReference.setStageTargets(
                constant(460.0, 7), false, sleepDurationRanges(), SLEEP_DURATION_RANGE_SIZE);
        assertArrayEquals(new double[]{450, 510, 390, 450}, r.stageTargetValues);
    }

    @Test
    public void setStageTargets_n3Range_targetsN3N1N3N2() {
        ExperimentEngineReference.StageTargets r = ExperimentEngineReference.setStageTargets(
                constant(525.0, 7), false, sleepDurationRanges(), SLEEP_DURATION_RANGE_SIZE);
        assertArrayEquals(new double[]{510, 390, 510, 450}, r.stageTargetValues);
    }

    @Test
    public void setStageTargets_overRange_targetsOverN3N1N2() {
        ExperimentEngineReference.StageTargets r = ExperimentEngineReference.setStageTargets(
                constant(600.0, 7), false, sleepDurationRanges(), SLEEP_DURATION_RANGE_SIZE);
        assertArrayEquals(new double[]{540, 510, 390, 450}, r.stageTargetValues);
    }

    @Test
    public void setStageTargets_ignoresNullInputs() {
        // Same as the underRange case, but with two missed check-in days interspersed.
        ExperimentEngineReference.StageTargets r = ExperimentEngineReference.setStageTargets(
                Arrays.asList(360.0, null, 360.0, 360.0, null, 360.0, 360.0), false,
                sleepDurationRanges(), SLEEP_DURATION_RANGE_SIZE);
        assertEquals(360.0, r.initialStageAverage, 1e-9);
        assertArrayEquals(new double[]{360, 390, 510, 450}, r.stageTargetValues);
    }

    @Test
    public void setStageTargets_variabilityStudy_usesMaxMinusMinNotMean() {
        // inputs are day-to-day sleep-start variances; average (stored regardless) is
        // the plain mean, but the branch selection uses (max - min).
        List<Double> inputs = Arrays.asList(0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0);
        ExperimentEngineReference.StageTargets r = ExperimentEngineReference.setStageTargets(
                inputs, true, sleepVariabilityRanges(), SLEEP_VARIABILITY_RANGE_SIZE);
        assertEquals(30.0, r.initialStageAverage, 1e-9); // mean(inputs), NOT the variability
        // variability = 60 - 0 = 60 <= N2(60)+15 -> N2 branch
        assertArrayEquals(new double[]{60, 90, 30, 60}, r.stageTargetValues);
    }

    private static void assertArrayEquals(double[] expected, double[] actual) {
        assertEquals(expected.length, actual.length);
        for (int i = 0; i < expected.length; i++) {
            assertEquals("index " + i, expected[i], actual[i], 1e-9);
        }
    }

    // ---- get_daily_target -------------------------------------------------------------

    @Test
    public void getDailyTarget_nonVariability_returnsStageTargetRegardlessOfParity() {
        assertEquals(Double.valueOf(390.0), ExperimentEngineReference.getDailyTarget(false, 390.0, 999.0, 0));
        assertEquals(Double.valueOf(390.0), ExperimentEngineReference.getDailyTarget(false, 390.0, 999.0, 1));
    }

    @Test
    public void getDailyTarget_nullStageTarget_returnsNull() {
        assertNull(ExperimentEngineReference.getDailyTarget(true, null, 30.0, 0));
        assertNull(ExperimentEngineReference.getDailyTarget(false, null, 30.0, 1));
    }

    @Test
    public void getDailyTarget_variability_alternatesAroundBaseline() {
        // base (initial_stage_average) = 30, stage_target (variability) = 60
        assertEquals(Double.valueOf(-30.0), ExperimentEngineReference.getDailyTarget(true, 60.0, 30.0, 0));
        assertEquals(Double.valueOf(90.0), ExperimentEngineReference.getDailyTarget(true, 60.0, 30.0, 1));
    }

    // ---- is_output_stable --------------------------------------------------------------

    @Test
    public void isOutputStable_stageZero_alwaysFalse() {
        assertFalse(ExperimentEngineReference.isOutputStable(0, constant(3.0, 7), 3.0));
    }

    @Test
    public void isOutputStable_noNonNullOutputs_false() {
        assertFalse(ExperimentEngineReference.isOutputStable(1, Arrays.asList(null, null, null), 3.0));
    }

    @Test
    public void isOutputStable_last5WithinRange_true() {
        assertTrue(ExperimentEngineReference.isOutputStable(1, constant(3.0, 7), 3.0));
    }

    @Test
    public void isOutputStable_last5OutsideRange_false() {
        assertFalse(ExperimentEngineReference.isOutputStable(1,
                Arrays.asList(1.0, 10.0, 3.0, 3.0, 3.0), 3.0));
    }

    // ---- get_valid_days -----------------------------------------------------------------

    @Test
    public void getValidDays_withTarget_filtersByRangeAndNulls() {
        List<Double> inputs = Arrays.asList(300.0, 360.0, 390.0, 420.0, null);
        List<Double> outputs = Arrays.asList(5.0, 6.0, 7.0, null, 8.0);
        List<ExperimentEngineReference.Pair> valid =
                ExperimentEngineReference.getValidDays(inputs, outputs, 390.0, 30.0);
        assertEquals(2, valid.size());
        assertEquals(360.0, valid.get(0).input, 1e-9);
        assertEquals(6.0, valid.get(0).output, 1e-9);
        assertEquals(390.0, valid.get(1).input, 1e-9);
        assertEquals(7.0, valid.get(1).output, 1e-9);
    }

    @Test
    public void getValidDays_nullTarget_onlyRequiresBothPresent() {
        List<Double> inputs = Arrays.asList(300.0, 360.0, 390.0, 420.0, null);
        List<Double> outputs = Arrays.asList(5.0, 6.0, 7.0, null, 8.0);
        List<ExperimentEngineReference.Pair> valid =
                ExperimentEngineReference.getValidDays(inputs, outputs, null, 30.0);
        assertEquals(3, valid.size());
    }

    // ---- get_num_missed_days -------------------------------------------------------------

    @Test
    public void getNumMissedDays_countsEitherSideNull() {
        List<Double> inputs = Arrays.asList(300.0, 360.0, null, 420.0, null);
        List<Double> outputs = Arrays.asList(5.0, null, 7.0, 8.0, 9.0);
        assertEquals(3, ExperimentEngineReference.getNumMissedDays(inputs, outputs));
    }

    // ---- should_end_stage -----------------------------------------------------------------

    @Test
    public void shouldEndStage_baselineStage_tooManyMissedDays_restarts() {
        ExperimentEngineReference.StageEndDecision d =
                ExperimentEngineReference.shouldEndStage(0, 5, 3, 4, false);
        assertFalse(d.shouldEnd);
        assertTrue(d.endedEarly);
        assertTrue(d.restartedStage);
    }

    @Test
    public void shouldEndStage_baselineStage_exactlyTwoMissed_notRestarted_endsOnDay7() {
        ExperimentEngineReference.StageEndDecision d =
                ExperimentEngineReference.shouldEndStage(0, 7, 2, 5, false);
        assertTrue(d.shouldEnd);
        assertFalse(d.endedEarly);
        assertFalse(d.restartedStage);
    }

    @Test
    public void shouldEndStage_laterStage_twoMissedDays_restarts() {
        ExperimentEngineReference.StageEndDecision d =
                ExperimentEngineReference.shouldEndStage(1, 3, 2, 1, false);
        assertFalse(d.shouldEnd);
        assertTrue(d.endedEarly);
        assertTrue(d.restartedStage);
    }

    @Test
    public void shouldEndStage_laterStage_fiveValidDaysAndStable_endsEarly() {
        ExperimentEngineReference.StageEndDecision d =
                ExperimentEngineReference.shouldEndStage(1, 3, 0, 5, true);
        assertTrue(d.shouldEnd);
        assertTrue(d.endedEarly);
        assertFalse(d.restartedStage);
    }

    @Test
    public void shouldEndStage_laterStage_stillPossibleToReachFourValidDays_continues() {
        // stageDay=4, validDays=3, daysLeft=3 -> possible=6, not < 4 -> continue
        ExperimentEngineReference.StageEndDecision d =
                ExperimentEngineReference.shouldEndStage(1, 4, 0, 3, false);
        assertFalse(d.shouldEnd);
        assertFalse(d.endedEarly);
        assertFalse(d.restartedStage);
    }

    @Test
    public void shouldEndStage_laterStage_cannotReachFourValidDays_restarts() {
        // stageDay=5, validDays=1, daysLeft=2 -> possible=3 < 4 -> restart
        ExperimentEngineReference.StageEndDecision d =
                ExperimentEngineReference.shouldEndStage(1, 5, 1, 1, false);
        assertFalse(d.shouldEnd);
        assertTrue(d.endedEarly);
        assertTrue(d.restartedStage);
    }

    @Test
    public void shouldEndStage_laterStage_day7NotStable_endsOnTime() {
        // stageDay=7, validDays=4, daysLeft=0 -> possible=4, not < 4 -> falls through to day==7 check
        ExperimentEngineReference.StageEndDecision d =
                ExperimentEngineReference.shouldEndStage(1, 7, 0, 4, false);
        assertTrue(d.shouldEnd);
        assertFalse(d.endedEarly);
        assertFalse(d.restartedStage);
    }

    // ---- calculate_results -----------------------------------------------------------------

    @Test
    public void calculateResults_maximize_picksHighestMeanStage_andComputesConfidence() {
        Map<Integer, Double> targets = new HashMap<>();
        targets.put(1, 30.0);
        targets.put(2, 60.0);
        targets.put(3, 90.0);

        Map<Integer, List<ExperimentEngineReference.Pair>> validDays = new HashMap<>();
        validDays.put(1, pairs(new double[]{1, 1, 1}, new double[]{5, 5, 5}));
        validDays.put(2, pairs(new double[]{1, 1, 1}, new double[]{8, 8, 8}));
        validDays.put(3, pairs(new double[]{1, 1, 1}, new double[]{6, 7, 8}));

        ExperimentEngineReference.Results results =
                ExperimentEngineReference.calculateResults(false, targets, validDays);

        assertEquals(2, results.bestStage);
        assertEquals(60.0, results.resultValue, 1e-9);
        // stage1 overlap (v>=best.min=8): 0/3=0; stage3 overlap (v>=8): 1/3=0.333 -> max=0.333
        // confidence = 1 - 0.333 = 0.67 (rounded), under the 0.9 cap
        assertEquals(0.67, results.resultConfidence, 1e-9);
    }

    @Test
    public void calculateResults_minimize_picksLowestMeanStage_andCapsConfidenceAt0point9() {
        Map<Integer, Double> targets = new HashMap<>();
        targets.put(1, 15.0);
        targets.put(2, 30.0);
        targets.put(3, 60.0);

        Map<Integer, List<ExperimentEngineReference.Pair>> validDays = new HashMap<>();
        validDays.put(1, pairs(new double[]{1, 1, 1}, new double[]{9, 9, 9}));
        validDays.put(2, pairs(new double[]{1, 1, 1}, new double[]{3, 3, 3}));
        validDays.put(3, pairs(new double[]{1, 1, 1}, new double[]{5, 6, 7}));

        ExperimentEngineReference.Results results =
                ExperimentEngineReference.calculateResults(true, targets, validDays);

        assertEquals(2, results.bestStage);
        assertEquals(30.0, results.resultValue, 1e-9);
        // both other stages have zero overlap with the winning stage's max(=3) -> confidence would be 1.0,
        // but the engine caps confidence at 0.9.
        assertEquals(0.9, results.resultConfidence, 1e-9);
    }

    private static List<ExperimentEngineReference.Pair> pairs(double[] inputs, double[] outputs) {
        List<ExperimentEngineReference.Pair> result = new java.util.ArrayList<>();
        for (int i = 0; i < inputs.length; i++) {
            result.add(new ExperimentEngineReference.Pair(inputs[i], outputs[i]));
        }
        return result;
    }
}
